ALTER TABLE "crm"."lookup_values" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "crm"."lookup_values" CASCADE;--> statement-breakpoint
ALTER TABLE "crm"."customer_documents" ADD CONSTRAINT "customer_documents_doc_type_check" CHECK ("crm"."customer_documents"."doc_type" IS NULL OR "crm"."customer_documents"."doc_type" IN ('면허증', '주민등록등본', '원천징수영수증', '사업자등록증', '부가세과세증명원', '소득금액증명원', '자동이체통장사본', '매매계약서', '리스승인서', '계약사실확인서', '법인(점)주주명부', '법인(점)등기부등본', '법인(점)법인인감증명서', '법인(점)개인인감증명서', '법인(점)재무제표(당해)', '법인(점)재무제표(전기)', '등록(점)자동차등록증', '등록(점)세금계산서', '등록(점)취득세납부영수증', '등록(점)등록비영수증', '등록(점)보험가입증명서', '기타서류'));--> statement-breakpoint
ALTER TABLE "crm"."customer_schedules" ADD CONSTRAINT "customer_schedules_type_check" CHECK ("crm"."customer_schedules"."type" IS NULL OR "crm"."customer_schedules"."type" IN ('재연락', '결정확인', '체크', '견적', '안내', '요청', '내부', '심사'));--> statement-breakpoint
ALTER TABLE "crm"."customer_tasks" ADD CONSTRAINT "customer_tasks_category_check" CHECK ("crm"."customer_tasks"."category" IS NULL OR "crm"."customer_tasks"."category" IN ('체크', '견적', '안내', '요청', '내부', '심사'));--> statement-breakpoint
ALTER TABLE "crm"."customers" ADD CONSTRAINT "customers_status_group_check" CHECK ("crm"."customers"."status_group" IS NULL OR "crm"."customers"."status_group" IN ('신규', '상담중', '견적', '차량체크', '심사서류', '관리중', '상담완료', '계약완료', '불발'));--> statement-breakpoint
ALTER TABLE "crm"."customers" ADD CONSTRAINT "customers_status_check" CHECK ("crm"."customers"."status" IS NULL OR "crm"."customers"."status" IN ('상담접수', '1차부재중', '지속적부재', '연락해야함', '구매방식상담중', '차량상담중', '견적상담중', '준비중', '발송완료', '추후안내예정', '재고확인중', '재고있음', '재고없음', '대기필요', '서류상담중', '서류안내함', '서류대기중', '서류받음', '부결후관리', '구매시기미도래', '추후재컨택', '조건재확인', '재상담대기', '딜러사계약중', '대리점발주중', '특판발주중', '배정완료', '출고완료', '계약취소', '구매철회'));--> statement-breakpoint
ALTER TABLE "crm"."customers" ADD CONSTRAINT "customers_chance_check" CHECK ("crm"."customers"."chance" IS NULL OR "crm"."customers"."chance" IN ('높음', '중간', '낮음', '보류', '확정'));--> statement-breakpoint
ALTER TABLE "crm"."customers" ADD CONSTRAINT "customers_source_check" CHECK ("crm"."customers"."source" IS NULL OR "crm"."customers"."source" IN ('앱 견적비교', '앱 AI상담', '앱 상담원 연결', '디엘(상담)', '디엘(견적서)', '대표전화', '카카오', '소개', '추천', '재구매', '유튜브', '검색', '기타'));--> statement-breakpoint
ALTER TABLE "crm"."customers" ADD CONSTRAINT "customers_customer_type_check" CHECK ("crm"."customers"."customer_type" IS NULL OR "crm"."customers"."customer_type" IN ('개인', '개인사업자', '법인사업자'));--> statement-breakpoint
ALTER TABLE "crm"."quote_scenarios" ADD CONSTRAINT "quote_scenarios_purchase_method_check" CHECK ("crm"."quote_scenarios"."purchase_method" IS NULL OR "crm"."quote_scenarios"."purchase_method" IN ('장기렌트', '운용리스', '금융리스', '중고리스', '할부', '일시불'));--> statement-breakpoint
ALTER TABLE "crm"."quotes" ADD CONSTRAINT "quotes_entry_mode_check" CHECK ("crm"."quotes"."entry_mode" IS NULL OR "crm"."quotes"."entry_mode" IN ('manual', 'solution', 'original'));--> statement-breakpoint
ALTER TABLE "crm"."quotes" ADD CONSTRAINT "quotes_app_status_check" CHECK ("crm"."quotes"."app_status" IS NULL OR "crm"."quotes"."app_status" IN ('draft', 'queued', 'sent', 'viewed'));--> statement-breakpoint
ALTER TABLE "crm"."quotes" ADD CONSTRAINT "quotes_decision_status_check" CHECK ("crm"."quotes"."decision_status" IS NULL OR "crm"."quotes"."decision_status" IN ('none', 'considering', 'confirmed', 'contracting'));--> statement-breakpoint
ALTER TABLE "crm"."quotes" ADD CONSTRAINT "quotes_acquisition_tax_mode_check" CHECK ("crm"."quotes"."acquisition_tax_mode" IS NULL OR "crm"."quotes"."acquisition_tax_mode" IN ('normal', 'hybrid', 'electric', 'manual'));--> statement-breakpoint
ALTER TABLE "crm"."quotes" ADD CONSTRAINT "quotes_status_check" CHECK ("crm"."quotes"."status" IS NULL OR "crm"."quotes"."status" IN ('고객 확인 전', '고객 열람'));